# generated by datamodel-codegen:
#   filename:  api-spec.yaml
#   timestamp: 2025-09-16T03:58:47+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class User(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None


class UserCreate(BaseModel):
    name: str
